"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Clock3, MapPin, PackageSearch, Save, ShieldCheck } from "lucide-react";
import {
  getWarehouseLocationOptions, getWarehouseReceiptById, getWarehouseReceiptItems,
  updateReceiptInspection, type CargoCondition, type WarehouseLocationOption,
  type WarehouseReceiptDetail, type WarehouseReceiptItem, type WarehouseReceiptStatus,
} from "../../../../lib/services/receiptService";
import { getReceiptMovements, type MovementWithLocations } from "../../../../lib/services/warehouseOperationsService";

const statusLabels: Record<string,string> = { draft:"Borrador", received:"Recibido", inspection:"En inspección", pending_documents:"Pendiente documentos", available:"Disponible", assigned_to_shipment:"Asignado", dispatched:"Despachado", cancelled:"Cancelado" };
const movementLabels: Record<string,string> = { receipt:"Recepción", location_assignment:"Asignación", relocation:"Reubicación", status_change:"Cambio de estado", inspection:"Inspección", dispatch:"Despacho", adjustment:"Ajuste" };
const conditions: {value:CargoCondition;label:string}[] = [{value:"good",label:"Buen estado"},{value:"damaged",label:"Dañada"},{value:"partial_damage",label:"Daño parcial"},{value:"open_box",label:"Caja abierta"},{value:"missing_pieces",label:"Faltan piezas"},{value:"wet",label:"Mojada"},{value:"unknown",label:"Sin verificar"}];

export default function ReceiptDetailPage() {
  const id = String(useParams()?.id || "");
  const [receipt,setReceipt]=useState<WarehouseReceiptDetail|null>(null); const [items,setItems]=useState<WarehouseReceiptItem[]>([]); const [locations,setLocations]=useState<WarehouseLocationOption[]>([]); const [movements,setMovements]=useState<MovementWithLocations[]>([]);
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState("");
  const fetchReceipt=useCallback(async()=>{if(!id)return;try{const [r,i,l,m]=await Promise.all([getWarehouseReceiptById(id),getWarehouseReceiptItems(id),getWarehouseLocationOptions(),getReceiptMovements(id)]);setReceipt(r);setItems(i);setLocations(l);setMovements(m);}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar la recepción.");}finally{setLoading(false);}},[id]);
  const load=useCallback(async()=>{setLoading(true);setError("");await fetchReceipt();},[fetchReceipt]);
  useEffect(()=>{
    if (!id) return;
    let active = true;
    Promise.all([getWarehouseReceiptById(id),getWarehouseReceiptItems(id),getWarehouseLocationOptions(),getReceiptMovements(id)])
      .then(([r,i,l,m])=>{if(active){setReceipt(r);setItems(i);setLocations(l);setMovements(m);}})
      .catch((e)=>{if(active)setError(e instanceof Error?e.message:"No se pudo cargar la recepción.");})
      .finally(()=>{if(active)setLoading(false);});
    return ()=>{active=false;};
  },[id]);
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!receipt)return;setSaving(true);setError("");setSuccess("");const f=new FormData(e.currentTarget);try{await updateReceiptInspection(id,{pieces:Number(f.get("pieces")),weight_kg:Number(f.get("weight")),length_cm:Number(f.get("length")),width_cm:Number(f.get("width")),height_cm:Number(f.get("height")),cargo_condition:String(f.get("condition")) as CargoCondition,has_visible_damage:f.get("damage")==="on",damage_notes:String(f.get("damage_notes")),location_id:String(f.get("location")),status:String(f.get("status")) as WarehouseReceiptStatus,notes:String(f.get("notes")),internal_notes:String(f.get("internal_notes")),operator_name:String(f.get("operator"))});setSuccess("Inspección guardada y movimiento registrado.");await load();}catch(err){setError(err instanceof Error?err.message:"No se pudo guardar.");}finally{setSaving(false);}}
  if(loading)return <div className="mx-auto max-w-6xl rounded-2xl border bg-white p-8 text-slate-500">Cargando recepción…</div>;
  if(!receipt)return <div className="mx-auto max-w-6xl rounded-2xl border bg-white p-8 text-red-700">{error||"Recepción no encontrada."}</div>;
  const locked=["dispatched","cancelled"].includes(receipt.status);
  const customsVerified=receipt.customs_status==="verified";
  const customsLabel={pending:"Pendiente",verified:"Verificado",held:"Retenido"}[receipt.customs_status];
  const customer=receipt.customers?.company_name||receipt.customers?.legal_name||"Cliente sin nombre";
  return <div className="mx-auto max-w-[1400px] space-y-6">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Link href="/warehouse/receipts" className="mb-3 inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-blue-700"><ArrowLeft size={16}/> Volver a recepciones</Link><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold text-slate-950">{receipt.wr_number}</h1><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{statusLabels[receipt.status]||receipt.status}</span></div><p className="mt-1 text-sm text-slate-500">{customer} · {receipt.description}</p></div>{!locked&&(customsVerified?<Link href={`/warehouse/dispatch/${receipt.id}`} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Facturar y preparar despacho</Link>:<Link href="/warehouse/customs-verification" className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white">Completar verificación de Aduanas</Link>)}</header>
    {error&&<Notice tone="red">{error}</Notice>}{success&&<Notice tone="green">{success}</Notice>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Summary icon={PackageSearch} label="Bultos" value={Number(receipt.pieces).toLocaleString("es-DO")}/><Summary icon={PackageSearch} label="Peso" value={`${Number(receipt.weight_kg).toLocaleString("es-DO")} kg`}/><Summary icon={MapPin} label="Ubicación" value={receipt.warehouse_locations?.code||"Sin ubicación"}/><Summary icon={CheckCircle2} label="Condición" value={conditions.find(c=>c.value===receipt.cargo_condition)?.label||receipt.cargo_condition}/><Summary icon={ShieldCheck} label="Aduanas" value={customsLabel}/></section>
    <section className="grid gap-6 xl:grid-cols-[1.4fr_.8fr]">
      <form onSubmit={save} className="rounded-2xl border bg-white p-5 shadow-sm sm:p-6"><div className="mb-5"><h2 className="text-lg font-bold">Control de inspección</h2><p className="text-sm text-slate-500">Los cambios quedan registrados en el historial de trazabilidad.</p></div><fieldset disabled={locked||saving} className="space-y-5 disabled:opacity-60"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Num name="pieces" label="Bultos verificados" value={receipt.pieces}/><Num name="weight" label="Peso KG" value={receipt.weight_kg} step="0.001"/><Num name="length" label="Largo CM" value={receipt.length_cm||0}/><Num name="width" label="Ancho CM" value={receipt.width_cm||0}/><Num name="height" label="Alto CM" value={receipt.height_cm||0}/><label className="text-sm font-semibold">Condición<select name="condition" defaultValue={receipt.cargo_condition} className="mt-1 w-full rounded-xl border px-3 py-2.5">{conditions.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</select></label></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Ubicación inicial<select name="location" defaultValue={receipt.location_id||""} className="mt-1 w-full rounded-xl border px-3 py-2.5"><option value="">Sin ubicación</option>{locations.map(l=><option key={l.id} value={l.id}>{l.code} · Zona {l.zone}</option>)}</select></label><label className="text-sm font-semibold">Resultado<select name="status" defaultValue={receipt.status} className="mt-1 w-full rounded-xl border px-3 py-2.5"><option value="received">Recibido</option><option value="inspection">En inspección</option><option value="pending_documents">Pendiente documentos</option><option value="available">Disponible para despacho</option></select></label></div><label className="flex items-center gap-3 rounded-xl border bg-slate-50 p-4 text-sm font-semibold"><input type="checkbox" name="damage" defaultChecked={receipt.has_visible_damage} className="h-5 w-5"/> Presenta daños visibles</label><Text name="damage_notes" label="Descripción de daños" value={receipt.damage_notes||""}/><div className="grid gap-4 sm:grid-cols-2"><Text name="notes" label="Observaciones" value={receipt.notes||""}/><Text name="internal_notes" label="Nota interna" value={receipt.internal_notes||""}/></div><label className="block text-sm font-semibold">Operador responsable *<input name="operator" required placeholder="Nombre y apellido" className="mt-1 w-full rounded-xl border px-3 py-2.5"/></label>{!locked&&<div className="flex justify-end"><button className="inline-flex items-center gap-2 rounded-xl bg-blue-700 px-5 py-2.5 text-sm font-semibold text-white"><Save size={17}/>{saving?"Guardando…":"Guardar inspección"}</button></div>}</fieldset>{locked&&<div className="mt-4 rounded-xl bg-slate-100 p-4 text-sm text-slate-600">Esta recepción está cerrada porque fue despachada o cancelada.</div>}</form>
      <div className="space-y-6"><div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">Información aduanal</h2><div className="mt-4 space-y-3"><Info label="Manifiesto" value={receipt.warehouse_manifests?.manifest_number}/><Info label="Master BL" value={receipt.warehouse_manifests?.master_bl}/><Info label="Contenedor" value={receipt.warehouse_manifests?.container_number}/><Info label="Sello" value={receipt.warehouse_manifests?.seal_number}/><Info label="Administración" value={receipt.warehouse_manifests?.customs_administration}/></div></div><div className="rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">Trazabilidad</h2><p className="text-sm text-slate-500">Historial de inspecciones y movimientos.</p></div><div className="max-h-[520px] divide-y overflow-y-auto">{movements.length?movements.map(m=><div key={m.id} className="flex gap-3 p-4"><div className="mt-1"><Clock3 size={17} className="text-blue-600"/></div><div><div className="text-sm font-bold">{movementLabels[m.movement_type]||m.movement_type}</div><div className="text-xs text-slate-500">{new Date(m.created_at).toLocaleString("es-DO")}{m.performed_by_name?` · ${m.performed_by_name}`:""}</div>{(m.from_location||m.to_location)&&<div className="mt-1 text-xs text-slate-600">{m.from_location?.code||"Sin ubicación"} → {m.to_location?.code||"Sin ubicación"}</div>}{m.notes&&<div className="mt-1 text-xs text-slate-600">{m.notes}</div>}</div></div>):<div className="p-6 text-sm text-slate-500">Aún no hay movimientos registrados.</div>}</div></div></div>
    </section>
    {items.length>0&&<section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="mb-4 font-bold">Detalle de la carga</h2><div className="overflow-x-auto"><table className="min-w-[700px] w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-3">#</th><th className="p-3">Descripción</th><th className="p-3">Bultos</th><th className="p-3">Peso KG</th><th className="p-3">HS Code</th></tr></thead><tbody className="divide-y">{items.map(i=><tr key={i.id}><td className="p-3">{i.item_number}</td><td className="p-3">{i.description}</td><td className="p-3">{i.pieces}</td><td className="p-3">{i.weight_kg}</td><td className="p-3">{i.hs_code||"-"}</td></tr>)}</tbody></table></div></section>}
  </div>;
}
function Num({name,label,value,step="1"}:{name:string;label:string;value:number;step?:string}){return <label className="text-sm font-semibold">{label}<input type="number" min="0" step={step} name={name} defaultValue={value} className="mt-1 w-full rounded-xl border px-3 py-2.5"/></label>}
function Text({name,label,value}:{name:string;label:string;value:string}){return <label className="block text-sm font-semibold">{label}<textarea name={name} defaultValue={value} rows={3} className="mt-1 w-full rounded-xl border px-3 py-2.5 font-normal"/></label>}
function Summary({icon:Icon,label,value}:{icon:typeof MapPin;label:string;value:string}){return <div className="flex gap-3 rounded-2xl border bg-white p-5 shadow-sm"><div className="rounded-xl bg-blue-50 p-3 text-blue-700"><Icon size={21}/></div><div><div className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</div><div className="mt-1 font-bold text-slate-950">{value}</div></div></div>}
function Info({label,value}:{label:string;value?:string|null}){return <div className="flex justify-between gap-4 border-b pb-2 text-sm last:border-0"><span className="text-slate-500">{label}</span><span className="text-right font-semibold">{value||"-"}</span></div>}
function Notice({tone,children}:{tone:"red"|"green";children:React.ReactNode}){return <div className={`rounded-xl border p-4 text-sm ${tone==="red"?"border-red-200 bg-red-50 text-red-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{children}</div>}
