"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Boxes, MapPin, Plus, RefreshCw, Warehouse } from "lucide-react";
import { getWarehouseReceipts, type WarehouseReceiptListItem } from "../../../lib/services/receiptService";
import { getWarehouseLocations } from "../../../lib/services/warehouseService";
import { createWarehouseLocation, moveWarehouseReceipt } from "../../../lib/services/warehouseOperationsService";
import type { WarehouseLocation, WarehouseReceiptStatus } from "../../../types/warehouse";

const activeStock = (r: WarehouseReceiptListItem) => !["dispatched", "cancelled"].includes(r.status);
const person = (r: WarehouseReceiptListItem) => r.customers?.company_name || r.customers?.legal_name || "Cliente sin nombre";

export default function InventoryPage() {
  const [receipts, setReceipts] = useState<WarehouseReceiptListItem[]>([]);
  const [locations, setLocations] = useState<WarehouseLocation[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const [showLocation, setShowLocation] = useState(false); const [selected, setSelected] = useState<WarehouseReceiptListItem | null>(null);
  const fetchInventory = useCallback(async () => { try { const [r,l] = await Promise.all([getWarehouseReceipts(), getWarehouseLocations()]); setReceipts(r); setLocations(l); } catch(e) { setError(e instanceof Error ? e.message : "No se pudo cargar el inventario."); } finally { setLoading(false); } }, []);
  const load = useCallback(async () => { setLoading(true); setError(""); await fetchInventory(); }, [fetchInventory]);
  useEffect(() => {
    let active = true;
    Promise.all([getWarehouseReceipts(), getWarehouseLocations()])
      .then(([r, l]) => { if (active) { setReceipts(r); setLocations(l); } })
      .catch((e) => { if (active) setError(e instanceof Error ? e.message : "No se pudo cargar el inventario."); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, []);
  const stock = useMemo(() => receipts.filter(activeStock), [receipts]);
  const occupied = new Set(stock.map((r) => r.location_id).filter(Boolean)).size;
  return <div className="mx-auto max-w-[1500px] space-y-6">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-sm font-bold uppercase tracking-wider text-blue-700"><Boxes size={18} /> Control físico</div><h1 className="text-3xl font-bold text-slate-950">Inventario y ubicaciones</h1><p className="mt-1 text-sm text-slate-500">Existencias por BL, zona, rack y posición con historial de movimientos.</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border bg-white p-2.5 text-slate-700" title="Actualizar"><RefreshCw size={19} /></button><button onClick={() => setShowLocation(true)} className="inline-flex items-center gap-2 rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={18} /> Nueva ubicación</button></div></header>
    {error && <Notice tone="red">{error}</Notice>}{success && <Notice tone="green">{success}</Notice>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={Boxes} label="Bultos bajo custodia" value={stock.reduce((s,r)=>s+Number(r.pieces||0),0).toLocaleString("es-DO")} /><Kpi icon={Warehouse} label="BL en almacén" value={stock.length.toString()} /><Kpi icon={MapPin} label="Ubicaciones activas" value={locations.length.toString()} /><Kpi icon={MapPin} label="Posiciones ocupadas" value={occupied.toString()} /></section>
    <section className="grid gap-6 xl:grid-cols-[1fr_2fr]">
      <div className="rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">Mapa de ubicaciones</h2><p className="text-sm text-slate-500">Carga asignada por posición.</p></div><div className="max-h-[650px] divide-y overflow-y-auto">{locations.length ? locations.map((l) => { const here=stock.filter(r=>r.location_id===l.id); return <div key={l.id} className="p-4"><div className="flex justify-between"><div><b>{l.code}</b><div className="text-xs text-slate-500">Zona {l.zone}{l.rack ? ` · Rack ${l.rack}`:""}{l.level ? ` · Nivel ${l.level}`:""}</div></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{here.length} BL</span></div><div className="mt-2 text-xs text-slate-500">{here.reduce((s,r)=>s+Number(r.pieces||0),0).toLocaleString("es-DO")} bultos</div></div>; }) : <div className="p-8 text-center text-sm text-slate-500">Cree la primera ubicación para comenzar.</div>}</div></div>
      <div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">Existencia actual</h2><p className="text-sm text-slate-500">Seleccione “Mover” para asignar o cambiar la ubicación.</p></div>{loading ? <div className="p-8 text-slate-500">Cargando inventario…</div> : <div className="overflow-x-auto"><table className="min-w-[800px] w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-3">WR / BL</th><th className="p-3">Cliente y carga</th><th className="p-3">Bultos</th><th className="p-3">Ubicación</th><th className="p-3">Estado</th><th className="p-3"></th></tr></thead><tbody className="divide-y">{stock.map(r=><tr key={r.id} className="hover:bg-slate-50"><td className="p-3"><Link href={`/warehouse/receipts/${r.id}`} className="font-bold hover:text-blue-700">{r.wr_number}</Link><div className="text-xs text-slate-500">{r.external_reference || "-"}</div></td><td className="p-3"><div className="font-medium">{person(r)}</div><div className="max-w-xs truncate text-xs text-slate-500">{r.description}</div></td><td className="p-3 font-semibold">{Number(r.pieces).toLocaleString("es-DO")}</td><td className="p-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${r.location_id?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-800"}`}>{r.warehouse_locations?.code || "Sin ubicación"}</span></td><td className="p-3 capitalize">{r.status.replaceAll("_"," ")}</td><td className="p-3"><button onClick={()=>setSelected(r)} className="rounded-lg bg-slate-950 px-3 py-2 text-xs font-semibold text-white">Mover</button></td></tr>)}</tbody></table></div>}</div>
    </section>
    {showLocation && <LocationModal onClose={()=>setShowLocation(false)} onDone={async()=>{setShowLocation(false);setSuccess("Ubicación creada correctamente.");await load();}} />}
    {selected && <MoveModal receipt={selected} locations={locations} onClose={()=>setSelected(null)} onDone={async()=>{setSelected(null);setSuccess("Movimiento registrado correctamente.");await load();}} />}
  </div>;
}

function LocationModal({onClose,onDone}:{onClose:()=>void;onDone:()=>void}) { const [saving,setSaving]=useState(false); const [error,setError]=useState(""); async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget);try{await createWarehouseLocation({code:String(f.get("code")),zone:String(f.get("zone")),rack:String(f.get("rack")),level:String(f.get("level")),position:String(f.get("position")),description:String(f.get("description"))});onDone();}catch(err){setError(err instanceof Error?err.message:"No se pudo crear.");setSaving(false);}} return <Modal title="Nueva ubicación" onClose={onClose}><form onSubmit={submit} className="space-y-4">{error&&<Notice tone="red">{error}</Notice>}<div className="grid gap-3 sm:grid-cols-2"><Field name="code" label="Código *" placeholder="A-01-01" required/><Field name="zone" label="Zona *" placeholder="A" required/><Field name="rack" label="Rack" placeholder="01"/><Field name="level" label="Nivel" placeholder="02"/><Field name="position" label="Posición" placeholder="03"/><Field name="description" label="Descripción" placeholder="Carga general"/></div><Actions onClose={onClose} saving={saving}/></form></Modal>; }
function MoveModal({receipt,locations,onClose,onDone}:{receipt:WarehouseReceiptListItem;locations:WarehouseLocation[];onClose:()=>void;onDone:()=>void}) { const [saving,setSaving]=useState(false);const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget);try{await moveWarehouseReceipt({receiptId:receipt.id,locationId:String(f.get("location")),status:String(f.get("status")) as WarehouseReceiptStatus,notes:String(f.get("notes")),operatorName:String(f.get("operator"))});onDone();}catch(err){setError(err instanceof Error?err.message:"No se pudo mover.");setSaving(false);}}return <Modal title={`Mover ${receipt.wr_number}`} onClose={onClose}><form onSubmit={submit} className="space-y-4">{error&&<Notice tone="red">{error}</Notice>}<label className="block text-sm font-semibold">Ubicación destino *<select name="location" required defaultValue={receipt.location_id||""} className="mt-1 w-full rounded-xl border px-3 py-2.5"><option value="">Seleccione…</option>{locations.map(l=><option key={l.id} value={l.id}>{l.code} · Zona {l.zone}</option>)}</select></label><label className="block text-sm font-semibold">Estado<select name="status" defaultValue={receipt.status} className="mt-1 w-full rounded-xl border px-3 py-2.5"><option value="received">Recibido</option><option value="inspection">En inspección</option><option value="pending_documents">Pendiente documentos</option><option value="available">Disponible</option></select></label><Field name="operator" label="Responsable *" placeholder="Nombre del operador" required/><Field name="notes" label="Motivo / observación *" placeholder="Asignación inicial, reubicación…" required/><Actions onClose={onClose} saving={saving}/></form></Modal>;}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold">{title}</h2><button onClick={onClose} className="text-slate-500">Cerrar</button></div>{children}</div></div>}
function Field(p:{name:string;label:string;placeholder:string;required?:boolean}){return <label className="block text-sm font-semibold">{p.label}<input {...p} className="mt-1 w-full rounded-xl border px-3 py-2.5 font-normal outline-none focus:ring-2 focus:ring-blue-200" /></label>}
function Actions({onClose,saving}:{onClose:()=>void;saving:boolean}){return <div className="flex justify-end gap-2 pt-2"><button type="button" onClick={onClose} className="rounded-xl border px-4 py-2 text-sm font-semibold">Cancelar</button><button disabled={saving} className="rounded-xl bg-blue-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving?"Guardando…":"Guardar"}</button></div>}
function Kpi({icon:Icon,label,value}:{icon:typeof Boxes;label:string;value:string}){return <div className="flex gap-4 rounded-2xl border bg-white p-5 shadow-sm"><div className="rounded-xl bg-blue-50 p-3 text-blue-700"><Icon size={22}/></div><div><div className="text-2xl font-bold">{value}</div><div className="text-sm text-slate-500">{label}</div></div></div>}
function Notice({tone,children}:{tone:"red"|"green";children:React.ReactNode}){return <div className={`rounded-xl border p-4 text-sm ${tone==="red"?"border-red-200 bg-red-50 text-red-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{children}</div>}
